kali_tool_dir: /tools
kali_directories:
  - path={{ kali_tool_dir }}
    mode="2770"
    owner=root
    group=git
  - path: /docs/
    mode: "2770"
    owner: root
    group: git
kali_groups:
  - git
  - sudo
kali_packages:
  - aptitude
  - ca-certificates
  - curl
  - chromium
  - docker-compose
  - git
  - libssl-dev
  - libffi-dev
  - locate
  - lsof
  - nmap
  - ntp
  - openssl
  - python-dev
  - python-pip
  - python-setuptools
  - rsh-client
  - sudo
  - tmux
  - ufw
  - unzip
  - wireshark
  - zsh
kali_packages_remove:
  - crda
  - cups
kali_pip_packages:
  # for analyze_hosts.py
  - ansible
  - awsscout2
  - bs4
  - cryptography
  #- dockerscan
  - manticore
  - paramiko
  - python-nmap
  - python-wappalyzer
  - requests
  - scapy
  - sslyze
  - xlrd
kali_git_info_repositories:
  # INFORMATIONAL
  - repo: https://github.com/felixgr/secure-ios-app-dev.git
    dest: /docs/secure-ios-app-dev.git
  - repo: https://github.com/GDSSecurity/Docker-Secure-Deployment-Guidelines.git
    dest: /docs/docker-secure-deployment-guidelines
  - repo: https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet
    dest: /docs/java-deserialisation-cheat-sheet
  - repo: https://github.com/FuzzySecurity/Resource-List
    dest: /docs/fuzzysec-resource-list
  - repo: https://github.com/mubix/post-exploitation-wiki
    dest: /docs/mubix-post-exploitation-wiki
  - repo: https://github.com/jshaw87/Cheatsheets
    dest: /docs/cheatsheets-jshaw87
  - repo: https://github.com/konstruktoid/hardening
    dest: hardening-ubuntu
  - repo: https://github.com/leostat/rtfm
    dest: rtfm
kali_binary_downloads:
  - url: http://www.ampliasecurity.com/research/wce_v1_42beta_x64.zip
    dest: binaries/wce_v1_42beta_x64.zip
  - url: http://www.ampliasecurity.com/research/wce_v1_42beta_x32.zip
    dest: binaries/wce_v1_42beta_x32.zip
  - url: http://www.oxid.it/downloads/ca_setup.exe
    dest: binaries/ca_setup.exe
  - url: https://github.com/gentilkiwi/mimikatz/releases/download/2.1.1-20170618/mimikatz_trunk.zip
    dest: binaries/mimikatz_trunk.zip
  - url: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: binaries/sysinternals-suite.zip
  - url: https://hashcat.net/files/hashcat-3.6.0.7z
    dest: binaries/hashcat-3.6.0.7z
  - url: https://github.com/AlessandroZ/LaZagne/releases/download/2.2/Windows.zip
    dest: binaries/LaZagne-2.2-windows.zip
#  - url: https://jitpack.io/com/github/frohoff/ysoserial/master-SNAPSHOT/ysoserial-master-SNAPSHOT.jar
#    dest: binaries/ysoserial-master.jar
  # - url: https://github.com/vulnersCom/burp-vulners-scanner/releases/download/1.1/burp-vulners-scanner-1.1.jar
  #   dest: burpplugins/vulners-scanner-1.1.jar
