- name: Clone Sparta repository
  git:
    repo=https://github.com/secforce/sparta.git
    dest=/tools/det
    accept_hostkey=yes
    version=master

- name: Install Sparta apt requirements
  apt:
    name="{{ item }}"
    update_cache=yes
    cache_valid_time=86400
    install-recommends=no
    state=present
  with_items:
    - python-elixir 
    - python-qt4 
    - xsltproc
    - nmap 
    - hydra 
    - cutycapt
    - ldap-utils 
    - rwho
    - rsh-client 
    - x11-apps 
    - finger