---
# file: kali.yml
- hosts: kali
  become: yes
  become_method: sudo
  roles:
    - role: PeterMosmans.bootstrap
      tags: bootstrap
    - role: PeterMosmans.provision-vagrant
      tags: vagrant
    - role: PeterMosmans.virtualbox-guest
      tags: virtualbox
    - role: PeterMosmans.compact-box
      tags: compact
  vars:
    - bootstrap_packages_remove: ""
    - hostname: kali
    - virtualbox_version: 5.1.6
    - virtualbox_x11: true
    - unnecessary_packages: ""
