---
# file: kali.yml
- hosts: kali
  become: yes
  become_method: sudo
  roles:
    - role: PeterMosmans.bootstrap
      tags: bootstrap
    - role: PeterMosmans.provision-vagrant
      tags: vagrant
    - role: PeterMosmans.virtualbox-guest
      tags: virtualbox
    - role: PeterMosmans.compact-box
      tags: compact
  vars:
    - bootstrap_packages_remove: ""
    - hostname: kali
    - virtualbox_version: 5.1.6
    - virtualbox_x11: true
    - sshd_config:
        - name: Banner
          value: /etc/issue.ssh
        - name: PasswordAuthentication
          value: "yes"
        - name: PermitEmptyPasswords
          value: "no"
        - name: PermitRootLogin
          value: "yes"
        - name: PubkeyAuthentication
          value: "yes"
        - name: RSAAuthentication
          value: "yes"
        - name: GSSAPIAuthentication
          value: "no"
        - name: UseDNS
          value: "no"
        - name: KexAlgorithms
          value: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
        - name: Ciphers
          value: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
        - name: MACs
          value: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com"
        - name: "HostKey /etc/ssh/ssh_host_rsa_key"
          value: ""
        - name: "HostKey /etc/ssh/ssh_host_ed25519_key"
          value: ""
    - unnecessary_packages: ""
