---
# file: ansible-server.yml
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: PeterMosmans.bootstrap
      tags: bootstrap
    - role: PeterMosmans.provision-vagrant
      tags: vagrant
    - role: PeterMosmans.virtualbox-guest
      tags: virtualbox
    - role: PeterMosmans.compact-box
      tags: compact
  vars:
    hostname: ansible-server
    virtualbox_version: 5.1.22
    bootstrap_commands: "chown vagrant:vagrant /home/vagrant/.ssh/config"
    bootstrap_packages:
      - sudo
      - ufw
      # Ansible:
      # - build-essential # unsure whether this is necessary
      - gcc
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-pip
    bootstrap_pip_packages:
      - ansible
    unnecessary_packages:
      # Remove Ansible-specific build stuff
      - gcc
      - libffi-dev
      - libssl-dev
      - python-dev
