---
# file: kali.yml
- hosts: kali
  become: yes
  become_method: sudo
  roles:
    - role: njones.kali
      tags: kali
  vars:
    - kali_packages_remove: ""
    - hostname: "njones-mwr-kali"
    - virtualbox_version: 5.1.10
    - virtualbox_x11: true
    - unnecessary_packages: ""
    - kali_directories:
        - path: /tools/
          mode: "2770"
          owner: root
          group: git
    - kali_pip_packages:
        # for analyze_hosts.py
        - python-nmap
        - requests
        - python-wappalyzer
        - scapy
        - ansible
        - cryptography
        - paramiko
        - bs4
        - sslyze
        - xlrd
    - kali_git_repositories:
        - repo: https://github.com/PeterMosmans/security-scripts
          dest: /tools/security-scripts
        - repo: https://github.com/drwetter/testssl.sh
          dest: /tools/testssl.sh
        - repo: https://github.com/PowerShellMafia/PowerSploit.git
          dest: /tools/PowerSploit
        - repo: https://github.com/danielmiessler/SecLists.git
          dest: /tools/SecLists
        - repo: https://github.com/trustedsec/egressbuster.git
          dest: /tools/egressbuster
        - repo: https://github.com/ShawnDEvans/smbmap.git
          dest: /tools/smbmap
        - repo: https://github.com/GDSSecurity/Windows-Exploit-Suggester.git
          dest: /tools/windows-exploit-suggester
        - repo: https://github.com/drwetter/testssl.sh.git
          dest: /tools/testssl.sh
        - repo: https://github.com/PenturaLabs/Linux_Exploit_Suggester.git
          dest: /tools/linux-exploit-suggester
        - repo: https://github.com/fuzzdb-project/fuzzdb.git
          dest: /tools/fuzzdb
        - repo: https://github.com/maldevel/PenTestKit.git
          dest: /tools/maldevel-pentestkit
        - repo: https://github.com/Trietptm-on-Security/Bella.git
          dest: /tools/bella
        - repo: https://github.com/fwaeytens/dnsenum.git
          dest: /tools/dnsenum
        - repo: https://github.com/internetwache/GitTools.git
          dest: /tools/gittools
        - repo: https://github.com/techgaun/github-dorks.git
          dest: /tools/github-dorks
        - repo: https://github.com/longld/peda.git
          dest: /tools/peda
        - repo: https://bitbucket.org/LaNMaSteR53/recon-ng.git
          dest: /tools/recon-ng
        - repo: https://github.com/mwrlabs/wePWNise.git
          dest: /tools/wepwnise
        - repo: https://github.com/samratashok/nishang.git
          dest: /tools/nishang
        - repo: https://github.com/jshaw87/Cheatsheets
          dest: cheatsheets-jshaw87
        - repo: https://github.com/makefu/dnsmap.git
          dest: /tools/dnsmap
    - kali_binary_downloads:
        - url: http://www.ampliasecurity.com/research/wce_v1_42beta_x64.zip
          dest: /tools/binaries/wce_v1_42beta_x64.zip
        - url: http://www.ampliasecurity.com/research/wce_v1_42beta_x32.zip
          dest: /tools/binaries/wce_v1_42beta_x32.zip
        - url: http://www.oxid.it/downloads/ca_setup.exe
          dest: /tools/binaries/ca_setup.exe
        - url: https://github.com/gentilkiwi/mimikatz/releases/download/2.1.1-20170618/mimikatz_trunk.zip
          dest: /tools/binaries/mimikatz_trunk.zip
        - url: https://download.sysinternals.com/files/SysinternalsSuite.zip
          dest: /tools/binaries/sysinternals-suite.zip
        - url: https://hashcat.net/files/hashcat-3.6.0.7z
          dest: /tools/binaries/hashcat-3.6.0.7z
    - kali_ufw_tcp_allow:
        - 22
