---
# file: kali.yml
- hosts: kali
  become: yes
  become_method: sudo
  roles:
    - role: njones.kali
      tags: kali
  vars:
    - kali_packages_remove: ""
    - hostname: "njones-mwr-kali"
    - virtualbox_version: 5.1.10
    - virtualbox_x11: true
    - unnecessary_packages: ""
    - kali_directories:
        - path: /tools/
          mode: "2770"
          owner: root
          group: git
    - kali_ufw_tcp_allow:
        - 22
