---
# defaults file for kali
kali_groups:
  - git
  - sudo
kali_packages:
  - aptitude
  - ca-certificates
  - curl
  - docker
  - docker-compose
  - git
  - libssl-dev
  - libffi-dev
  - locate
  - lsof
  - nmap
  - ntp
  - openssl
  - python-dev
  - python-pip  
  - python-setuptools
  - sudo
  - tmux
  - ufw
  - unzip
  - wireshark
  - zsh
kali_packages_remove:
  - crda
  - cups
kali_templates:
  - src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
  - src: issue.ssh.j2
    dest: /etc/issue.ssh
    mode: "0644"
  - src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
company: "Nick Jones"
grub_settings:
  - name: "GRUB_TIMEOUT"
    value: "0"
  - name: "GRUB_RECORDFAIL_TIMEOUT"
    value: "0"
sshd_banner: /etc/issue.ssh
sshd_ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
sshd_gssapiauthentication: "no"
sshd_hostkeyalgorithms: "ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa"
sshd_kexalgorithms: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
sshd_macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com"
sshd_moduli_remove:
  - 1023
  - 1535
sshd_passwordauthentication: "yes"
sshd_permitemptypasswords: "no"
sshd_permitrootlogin: "no"
sshd_pubkeyauthentication: "yes"
sshd_rsaauthentication: "yes"
sshd_usedns: "no"
sshd_usepam: "yes"
sshd_x11forwarding: "no"
timezone: Etc/UTC