---
# file: ansible-server.yml
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: PeterMosmans.bootstrap
      tags: bootstrap
    - role: PeterMosmans.virtualbox-guest
      tags: virtualbox
    - role: PeterMosmans.provision-vagrant
      tags: vagrant
    - role: PeterMosmans.compact-box
      tags: compact
  vars:
    - bootstrap_packages:
      - aptitude
      - ca-certificates
      - curl
      - git
      - locate
      - lsof
      - ntp
      - openssl
      - sshpass
      - sudo
      - tmux
      - ufw
      - unzip
      - zsh
    - hostname: ansible-server
    - virtualbox_version: 5.1.8
