# tasks file for kali

- name: Make directory for git repositories
  file:
    path={{ tools_dir }}
    state=directory
    mode=0755

- name: Install common git repositories
  git:
    repo={{ item.repo }}
    dest={{tools_dir}}/{{ item.dest }}
    accept_hostkey=yes
    version={{ item.version|default(\"master\") }}
    force={{ item.force|default("no") }}
  with_items:
    - "{{ kali_git_repositories|default([]) }}"
  # local modifications allowed
  ignore_errors: yes

- name: Generate tools listing
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    mode={{ item.mode }}
  with_items:
    - "{{ kali_templates|default([]) }}"
  tags:
    - templates

